[build]
  functions = "functions/"
  publish = "public/"

[[plugins]]
  package = "netlify-plugin-form-submissions"

  [plugins.inputs]
    formNames = "sampleApprovedComments"
    dataDirectory = "public/_data"
